// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPd5ET3axBn4lAynVMSRAukPDYh3NfZ9I',
    appId: '1:219016325411:web:5ec23f4548dd189bd6c496',
    messagingSenderId: '219016325411',
    projectId: 'agendacontatos-94a28',
    authDomain: 'agendacontatos-94a28.firebaseapp.com',
    storageBucket: 'agendacontatos-94a28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzkPhtSX7CTYia3lHZgfIMWXVE4gJ4x9w',
    appId: '1:219016325411:android:834adebf171f8b52d6c496',
    messagingSenderId: '219016325411',
    projectId: 'agendacontatos-94a28',
    storageBucket: 'agendacontatos-94a28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkMJlSJ5mtK-Wib5Id7AL9ARQAJlfwRi0',
    appId: '1:219016325411:ios:b3f77797c970b210d6c496',
    messagingSenderId: '219016325411',
    projectId: 'agendacontatos-94a28',
    storageBucket: 'agendacontatos-94a28.appspot.com',
    iosBundleId: 'com.example.flutterAgenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkMJlSJ5mtK-Wib5Id7AL9ARQAJlfwRi0',
    appId: '1:219016325411:ios:b3f77797c970b210d6c496',
    messagingSenderId: '219016325411',
    projectId: 'agendacontatos-94a28',
    storageBucket: 'agendacontatos-94a28.appspot.com',
    iosBundleId: 'com.example.flutterAgenda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPd5ET3axBn4lAynVMSRAukPDYh3NfZ9I',
    appId: '1:219016325411:web:04cc8b24b763c8bdd6c496',
    messagingSenderId: '219016325411',
    projectId: 'agendacontatos-94a28',
    authDomain: 'agendacontatos-94a28.firebaseapp.com',
    storageBucket: 'agendacontatos-94a28.appspot.com',
  );
}
